# Generated by Django 3.0.7 on 2020-06-05 23:26

import datetime
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=80, null=True)),
                ('make', models.CharField(max_length=50, null=True)),
                ('model', models.CharField(max_length=50, null=True)),
                ('picture', models.ImageField(null=True, upload_to='profiles')),
                ('time_duration', models.CharField(max_length=70, null=True)),
                ('price', models.CharField(max_length=80, null=True)),
                ('km_price', models.CharField(max_length=90, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=5, null=True)),
                ('make', models.CharField(max_length=40, null=True)),
                ('model', models.CharField(max_length=40, null=True)),
                ('price', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='cites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=40)),
                ('city_state', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='claim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_no', models.IntegerField()),
                ('veh_no', models.CharField(max_length=5, null=True)),
                ('mobile', models.BigIntegerField(null=True)),
                ('email', models.CharField(max_length=20, null=True)),
                ('m_name', models.CharField(max_length=20, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('engine', models.CharField(max_length=20, null=True)),
                ('chassis', models.CharField(max_length=20, null=True)),
                ('seat', models.CharField(max_length=20, null=True)),
                ('fuel', models.CharField(max_length=20, null=True)),
                ('reason', models.CharField(max_length=20, null=True)),
                ('usage', models.CharField(max_length=20, null=True)),
                ('cc', models.IntegerField(null=True)),
                ('proof', models.ImageField(null=True, upload_to='proof')),
            ],
        ),
        migrations.CreateModel(
            name='document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('pic', models.ImageField(upload_to='profiles')),
            ],
        ),
        migrations.CreateModel(
            name='document1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_duration', models.CharField(max_length=70)),
                ('price', models.CharField(max_length=80)),
                ('km_price', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='driverupdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='profiles')),
                ('picture1', models.ImageField(upload_to='profiles')),
            ],
        ),
        migrations.CreateModel(
            name='insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veh_state', models.CharField(max_length=20, null=True)),
                ('veh_code', models.CharField(max_length=5, null=True)),
                ('veh_ser', models.CharField(max_length=2, null=True)),
                ('veh_no', models.IntegerField(null=True)),
                ('price', models.IntegerField(null=True)),
                ('mobile', models.BigIntegerField(null=True)),
                ('email', models.CharField(max_length=20, null=True)),
                ('m_name', models.CharField(max_length=20, null=True)),
                ('carmodel', models.CharField(max_length=20, null=True)),
                ('city', models.CharField(max_length=20, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('ex_date', models.DateTimeField(default=datetime.datetime(2021, 6, 6, 4, 56, 27, 656377))),
                ('year', models.CharField(max_length=20, null=True)),
                ('engine', models.CharField(max_length=20, null=True)),
                ('chassis', models.CharField(max_length=20, null=True)),
                ('seat', models.CharField(max_length=20, null=True)),
                ('fuel', models.CharField(max_length=20, null=True)),
                ('cc', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='orderplace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicalnumber', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=50000)),
                ('gender', models.CharField(max_length=859)),
            ],
        ),
        migrations.CreateModel(
            name='plan_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40, null=True)),
                ('state', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=90)),
                ('vehical_number', models.CharField(max_length=40)),
                ('vehical_purchase_month', models.CharField(max_length=40, null=True)),
                ('vehical_purchase_year', models.CharField(max_length=40, null=True)),
                ('make', models.CharField(max_length=40)),
                ('model', models.CharField(max_length=40)),
                ('category', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='rantal_search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_up_city_name', models.CharField(max_length=60)),
                ('drop_up_city_name', models.CharField(max_length=60)),
                ('pick_up_date_time', models.CharField(max_length=60, null=True)),
                ('drop_up_date_time', models.CharField(max_length=60, null=True)),
                ('make', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='rental_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField(null=True)),
                ('price', models.IntegerField(null=True)),
                ('email', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='rto_code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(max_length=40, null=True)),
                ('place', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='towing_plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30, null=True)),
                ('standerd', models.IntegerField(null=True)),
                ('elite', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='towing_plan_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20, null=True)),
                ('price', models.CharField(max_length=6, null=True)),
                ('state', models.CharField(max_length=20, null=True)),
                ('city', models.CharField(max_length=20, null=True)),
                ('rto', models.CharField(max_length=20, null=True)),
                ('number', models.IntegerField(null=True)),
                ('month', models.CharField(max_length=20, null=True)),
                ('year', models.CharField(max_length=20, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('make', models.CharField(max_length=20, null=True)),
                ('model', models.CharField(max_length=20, null=True)),
                ('series', models.CharField(max_length=20, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='vehical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehical_number', models.CharField(max_length=50)),
                ('vehical_purchase_date', models.CharField(max_length=50)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealer_name', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=40)),
                ('state', models.CharField(max_length=40)),
                ('contect_no', models.BigIntegerField()),
                ('contect_person', models.CharField(max_length=40)),
                ('type_of_vehical', models.CharField(max_length=40)),
                ('manufacture', models.CharField(max_length=100)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.cites')),
            ],
        ),
        migrations.CreateModel(
            name='branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=40)),
                ('state', models.CharField(max_length=40)),
                ('contect_no', models.BigIntegerField()),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.cites')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('city', models.CharField(max_length=20, null=True)),
                ('state', models.CharField(max_length=20, null=True)),
                ('mid_name', models.CharField(max_length=20, null=True)),
                ('mobile', models.BigIntegerField(null=True)),
                ('dob', models.CharField(max_length=10, null=True)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=6)),
                ('address', models.CharField(max_length=30)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
