# Generated by Django 3.0.7 on 2020-06-05 23:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='ex_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 6, 4, 57, 10, 191907)),
        ),
    ]
