# Generated by Django 3.0.2 on 2020-06-05 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200606_0457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='ex_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 5, 22, 30, 14, 330828)),
        ),
    ]
