# Generated by Django 3.0.2 on 2020-03-01 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_garage_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=5)),
                ('make', models.CharField(max_length=40)),
                ('model', models.CharField(max_length=40)),
            ],
        ),
    ]
