# Generated by Django 3.0.2 on 2020-02-06 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_coustomer',
            new_name='is_insurance',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_employee',
            new_name='is_rental',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='is_towing',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='document',
        ),
    ]
