# Generated by Django 3.0.2 on 2020-06-05 20:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200605_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverupdate',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles'),
        ),
        migrations.AlterField(
            model_name='driverupdate',
            name='picture1',
            field=models.ImageField(blank=True, null=True, upload_to='profiles'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='ex_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 6, 1, 30, 7, 786062)),
        ),
    ]
