# Generated by Django 3.0.3 on 2020-02-12 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200206_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_insurance',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_rental',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_towing',
        ),
    ]
