# Generated by Django 3.0.2 on 2020-06-05 20:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200606_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='ex_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 6, 1, 36, 3, 789366)),
        ),
    ]
