# Generated by Django 3.0.2 on 2020-06-06 06:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200606_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='proof',
            field=models.ImageField(blank=True, null=True, upload_to='proof'),
        ),
        migrations.AlterField(
            model_name='document',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='profiles'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='ex_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 6, 11, 46, 22, 650878)),
        ),
    ]
