# Generated by Django 3.0.2 on 2020-06-06 06:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200606_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='ex_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 6, 11, 52, 24, 927748)),
        ),
    ]
