from django.urls import path
from . import views
from django.contrib.auth import views as v
from .views import *

urlpatterns = [
    path('handlerequest/',views.handlerequest,name='handlerequest'),
    path('plan_towing/',views.plan_towing,name='plan_towing'),
    path('',views.index_page,name='index'),
    path('master/',views.master_page,name='master'),
    path('register/',views.register_page,name='register'),
    path('login/',views.login_page,name='login'),
    path('rantal/',views.rantal_page,name='rantal'),
    path('towing/',views.towing_page,name='towing'),
    path('insurance/',views.insurance_page,name='insurance'),
    path('logout/',views.log_out,name='logout'),
    path('car_insurance/',views.car_insurance,name='c_insurance'),
    path('renew/',views.renew_page,name='renew'),
   # path('insurance_master/',views.insurance_master_page,name='ins_master'),
    path('car_claim/',views.carclaim_page,name='c_claim'),
    path('contect/',views.contect_page,name='contect'),
    path('customer_support_page/',views.customer_support_page,name='customer_support_page'),
    path('grievance_page/',views.grievance_page,name='grievance_page'),
    path('garage_list',views.garage_list_page,name='garage_list'),
    path('otp',views.policy_otp_page,name='otp_policy'),
    path('policyno',views.policy_no_page,name='policy_no'),
    path('get_city',views.get_city,name='get_city'),
    path('mainpage',views.head_page,name='head'),
    path('get_manufacture',views.get_manufacture,name='get_manufacture'),
    path('select_plan/',views.select_plan_page,name='select_plan'),
    path('confirm_detail_insurance/<str:rto>/<str:series>/<str:stat>/<str:number>/<str:make>/<str:model>/<str:year>/<str:engine>/<str:chassis>/<str:seat>/<str:fuel>/<str:city>/<str:cc>',views.confirm_detail_insurance,name='confirm_detail_insurance'),
    path('plan_detail',views.paln_detail_page,name='plan_detail'),
    path('expert_blog',views.expert_blog_page,name='expert_blog'),
    path('insurance_info',views.insurance_information_page,name='insurance_info'),
    path('car_info',views.car_insurance_information_page,name='car_info'),
    path('car_act',views.car_act_page,name='car_act'),
    path('parking_tips',views.parking_tips_page,name='parking_tips'),
    path('micro_dot',views.microdot_page,name='micro_dot'),
    path('thired_party_detail',views.thired_party_detail_page,name='thired_party_detail'),
    path('new_rules',views.new_rules_page,name='new_rules'),
    path('tuch_less',views.tuch_less_page,name='tuch_less'),
    path('branches',views.branch_page,name='branches'),
    path('get_branches',views.get_branches,name='get_branches'),
    path('detail',views.detail_page,name='detail'),
    path('get_make',views.get_make,name='get_make'),
    path('get_state_city',views.get_state_city,name='get_state_city'),
    path('privacy_policy_page',views.privacy_policy_page,name='privacy_policy_page'),
    path('insurance_app_policy_page',views.insurance_app_policy_page,name='insurance_app_policy_page'),
    path('terms_condition_page',views.terms_condition_page,name='terms_condition_page'),
    path('disclamer_page',views.disclamer_page,name='disclamer_page'),
    path('get_make_model',views.get_make_model,name='get_make_model'),
    path('plan_detail_insurance_page',views.plan_detail_insurance_page,name='plan_detail_insurance_page'),
    path('get_rto_code/',views.get_rto_code,name='get_rto_code'),
    path('get_place/',views.get_place,name='get_place'),
    path('download',views.download,name='download'),
    path('claim_form_page/<str:rto>/<str:series>/<str:stat>/<str:number>/<str:make>/<str:model>/<int:id>/<str:engine>/<str:chassis>/<str:seat>/<str:fuel>/<str:cc>',views.claim_form_page,name='claim_form_page'),
    path('feedback',views.feedback_page,name='feedback'),
    path('payment',views.payment,name='payment'),
    path('policy',views.policy,name='policy'),
    path('faq_insurance_page',views.faq_insurance_page,name='faq_insurance_page'),
    path('overview_page',views.overview_page,name='overview_page'),
    path('who_we_page',views.who_we_page,name='who_we_page'),
    path('promoter_page',views.promoter_page,name='promoter_page'),
    path('info_center_page',views.info_center_page,name='info_center'),
    #towing
    path('formfillup',views.formfillup,name='formfillup'),
    path('demo',views.demo,name='demo'),
    path('Towingpayment',views.Towingpayment,name='Towingpayment'),
    path('Towinghandlerequest/',views.Towinghandlerequest,name='Towinghandlerequest'),
    path('index/',views.index_towing_page,name='index'),
    path('accidenttowing',views.ac_towing,name='ac_towing'),
    path('bat_jump',views.bat_jump,name='bat_jump'),
    path('flat_tyre',views.flat_tyre,name='flat_tyre'),
    path('lost_key',views.lost_key,name='lost_key'),
    path('fuel_pro',views.fuel_pro,name='fuel_pro'),
    path('2wheel',views.twowheel,name='2wheel'),
    path('4wheel',views.fourwheel,name='4wheel'),
    path('faq',views.faq,name='faq'),
    path('contact',views.contact,name='contact'),
    path('about',views.about,name='about'),
    path('covrage',views.covrage,name='covrage'),
    path('plans',views.plans,name='plans'),
    path('bat_plans',views.bat_plans,name='bat_plans'),
    path('flat_plans',views.flat_plans,name='flat_plans'),
    path('lost_plans',views.lost_plans,name='lost_plans'),
    path('fuel_plans',views.fuel_plans,name='fuel_plans'),
    path('towing_plan/<str:cat>/<str:price>',views.towing_plan,name='towing_plan'),
    path('profile_tow/<int:id>',views.profile_tow,name='profile_tow'),
    path('profile_ins/<int:id>',views.profile_ins,name='profile_ins'),
    path('email_valid',views.email_valid,name='email_valid'),
    path('mobile_valid',views.mobile_valid,name='mobile_valid'),
    path('email_match',views.email_match,name='email_match'),
    path('turms_condition_towing',views.turms_condition_towing_page,name='turms_condition_towing'),


    #rantal
     path('display',views.display,name="display"),
     path('Rentalpayment',views.Rentalpayment,name='Rentalpayment'),
    path('Rentalhandlerequest/',views.Rentalhandlerequest,name='Rentalhandlerequest'),
    path('rental_master',views.rental_master_page,name="rental_master"),
    path('rental_home_page',views.rental_home_page,name="rental_home_page"),
     path('vehical_detail',views.vehical_detail,name='vehical_detail'),
    #path('rental_home',views.rental_home,name='rental_home'),
    path('rental_city',views.rental_city,name='rental_city'),
    path('upload',views.upload,name='upload'),
    path('prac<int:id><int:id1>',views.prac,name='prac'),
    path('master1',views.master1,name='master1'),
    path('offer',views.offer,name='offer'),  
    path('try',views.tries,name='try'),
    path('password-change/',v.PasswordChangeView.as_view(template_name='password_change.html'),name='change_password'),
 
    path('password-change-done/', v.PasswordChangeDoneView.as_view(template_name='password_change_done.html'),name='password_change_done'),
    path('eli',views.eli,name='eli'), 
    path('member',views.member,name='member'),
    path('driverupload<int:id><int:id1>',views.driverupload,name="driverupload"),
    path('rto',views.rto,name='rto'),
    path('helpcenter',views.helpcenter,name='helpcenter'),
    path('homepage',views.homepage,name='homepage'),
    path('confirmorder<int:id><int:id1>',views.confirmorder,name='confirmorder'),
    path('profile<int:id><int:id2>',views.profile,name='profile'),
    path('password-reset/', v.PasswordResetView.as_view(template_name='password_reset.html', email_template_name='password_reset_email.html',subject_template_name='password_reset_email_subject.txt'),name='password_reset'),
    path('password-reset-done/', v.PasswordResetDoneView.as_view(template_name='password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>', v.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', v.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'), name='password_reset_complete'),
    path('booking',views.booking,name='booking'),
    path('mybooking',views.mybooking,name='mybooking'),
    path('log',views.log,name='log'),
    path('cancel<int:id>',views.cancel,name='cancel'),
 

   
]